use demodb;
drop table raw_json;
drop table raw_xml;
drop table sv_aggregate;
drop table sv_json_data;
drop table sv_json_data_master;
drop table xml_data_archive;
drop function convertX2J;
drop function convertJArr2Obj;
drop database demodb;
